In [1]:
import numpy as np

#### (1) FOR LOOP PRACTICE
- (a.) Create a *list* consisting of the names of YOUR three favorite cities: 
<br><br>
- (b.) Write a for loop that prints out the name of each of these cities!
<br><br>

*Recall that this could be done as:*
<br>
&emsp;for i in range(3):<br>
&emsp;&emsp;print(list[i])
<br>

where *range(3)* is the iterable object -> but in your lesson, we also talked about another, more Pythonic way to do this where the data itself is the *iterable object*

In [2]:
fav_cities = ['Baltimore','Boston','Washington D.C.']

In [3]:
for city in fav_cities:
    print(city)

Baltimore
Boston
Washington D.C.


#### (2) WHILE LOOP PRACTICE
- (a.) construct a while loop to sum up the values of 1 through 9, and then print out the sum after the loop is done, as well as the value of i

In [ ]:

# Answer: 45!

i=1
sum=0
while i < 10:
    sum = sum + i # Add i to running sum
    i=i+1
    

print(sum)
print(i)

45
10


#### (3) ARRAY OPERATIONS
- (a.) Convert the temperatures in array d, which are in degrees Fahrenheit, to degrees Celsius, using array operations, and save to a new variable (i.e., *don't overwrite d*)
<br><br>
- (b.) Convert array d to an 1D array and save to a new variable (i.e., *don't overwrite d*)

In [8]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,97,92,90,95],[93,87,98,96,93,89]])
print(d)

[[100  94  97  92  90  95]
 [ 93  87  98  96  93  89]]


In [9]:
new_d = (d-32) * (5/9)
print(new_d)

[[37.77777778 34.44444444 36.11111111 33.33333333 32.22222222 35.        ]
 [33.88888889 30.55555556 36.66666667 35.55555556 33.88888889 31.66666667]]


In [10]:
d1 = d.flatten()
print(d1)

[100  94  97  92  90  95  93  87  98  96  93  89]


#### (4) ARRAY COMPARISON + LOGICAL OPERATIONS 
***REMINDER: USE ARRAY IN DEGREES FAHRENHEIT FOR ALL QUESTIONS IN 4***
- (a.) identify and print only elements in array d that are above 95

In [ ]:
# Flatten array
d1 = d.flatten()

# Loop through elements in array
for t in d1:
    if t > 95: 
        print(t)


100
97
98
96


- (b.) identify and print elements in array d that are above 95 AND are divisble by 2

In [19]:
# Flatten array
d1 = d.flatten()

# Loop through elements in array
for t in d1:
    if t > 95:
        if t % 2 == 0: 
            print(t) 

100
98
96


- (c.) calculate how many elements in d are above 95

In [21]:
print(np.sum(d > 95))
# Answer: 4 (using array in deg F)

4


- (d.) calculate the mean of all elements in d that are above 95

In [33]:
print(np.mean(d[np.where(d>95)]))

# Answer: 97.75 (using array in deg F)

97.75
