- import numpy package as alias 'np'

In [1]:
import numpy as np

# Array creation:
*please use NumPy functions rather than doing so manually*
- Create a 1D array, a, that consists of elements 1 through 10 (inclusive)
- Create a 1D array, b, that consists of elements 11 through 20 (inclusive)

In [5]:

# print(a) gives you [ 1  2  3  4  5  6  7  8  9 10]
a = np.arange(1,11,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:

# print(b) gives you [11 12 13 14 15 16 17 18 19 20]
b = np.arange(11,21,1)
print(b)

[11 12 13 14 15 16 17 18 19 20]


- Add arrays a and b together and save the result in array c
  - Can use built-in Python operations, although you'll learn more options next week about mathematical operations in NumPy!

In [7]:

# print(c) should equal [12 14 16 18 20 22 24 26 28 30]
c = np.add(a,b)
print(c)

[12 14 16 18 20 22 24 26 28 30]


# Array indexing

In [8]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,96,92,90],[95,87,98,96,93]])
print(d)

[[100  94  96  92  90]
 [ 95  87  98  96  93]]


- Access and print the element in the first row, third column of d


In [10]:

# this element is 96
print(d[0,2])

96


- Access and print the elements in the second row, and the first through fourth (inclusive) columns of d

In [12]:

# this array subset is [95 87 98 96]
print(d[1,:4])

[95 87 98 96]


# Array Characteristics
- calculate and print the maximum and minimum values in d

In [13]:
print(np.max(d))
# max is 100

print(np.min(d))
# min is 87


100
87


- calculate and print the shape of d
- in a comment, describe how many rows and columns d has

In [14]:

# shape is (2,5) 
print(np.shape(d))

(2, 5)


- calculate the size of d

In [15]:

# size is 10
print(np.size(d))

10
